### ISSUE TITLE
Creating waypoints does not work

### ISSUE THREAD

**Issue by viktordimov** [Fisch37/waypoints-vanilla#6]
# Bug Description
Adding a Book and Quill and an Enderpearl to the crafting table does nothing.

# Expected Behaviour
Expected to get a signable Book and Quill
![expected](https://cdn.modrinth.com/data/BU29E4fk/images/95be695e60c3808b6384ea6fae9ad9124b638440.png)

# Steps to Reproduce
1. Go to 'crafting table'
2. Add Book and Quill and Enderpearl

# Used Version
Mod version v1.0-Beta.5

# Additional Specifications
Using fabric.

<details>
<summary> Mods </summary>

  [✔️] AdvancementPlaques-1.20.4-fabric-1.5.1.jar
  [✔️] architectury-11.1.13-fabric.jar
  [✔️] areas-1.20.4-5.3.jar
  [✔️] BadOptimizations-2.1.0.jar
  [✔️] balm-fabric-1.20.4-9.0.6.jar
  [✔️] BarteringStation-v20.4.1-1.20.4-Fabric.jar
  [✔️] beautify-1.2.0+1.20.4.jar
  [✔️] bedrockify-1.9.1+mc1.20.4.jar
  [✔️] betterarcheology-1.1.6-1.20.4.jar
  [✔️] better-enchanted-books-1.20.4-1.4.4.jar
  [✔️] BetterF3-9.0.0-Fabric-1.20.4.jar
  [✔️] blur-3.2.0.jar
  [✔️] bobby-5.1.0+mc1.20.4.jar
  [✔️] book_and_quick_save-1.0.jar
  [✔️] Bookshelf-Fabric-1.20.4-23.0.5.jar
  [✔️] brb-1.10.0+1.20.4.jar
  [✔️] c2me-fabric-mc1.20.4-0.2.0+alpha.11.58.jar
  [✔️] calcmod-fabric-1.20.2-1.3.1.jar
  [✔️] camps_castles_carriages-2.2.jar
  [✔️] cardinal-components-api-5.4.0.jar
  [✔️] cc-tweaked-1.20.4-fabric-1.109.6.jar
  [✔️] chat_heads-0.10.31-fabric-1.20.3.jar
  [✔️] chatanimation-1.0.5.jar
  [✔️] cherishedworlds-fabric-8.0.0+1.20.4.jar
  [✔️] Chunky-1.3.138.jar
  [✔️] cloth-config-13.0.121-fabric.jar
  [✔️] collective-1.20.4-7.36.jar
  [✔️] CompletionistsIndex-v20.4.1-1.20.4-Fabric.jar
  [✔️] continuity-3.0.0-beta.4+1.20.2.jar
  [✔️] Controlling-fabric-1.20.4-15.0.2.jar
  [✔️] cookingforblockheads-fabric-1.20.4-18.0.3.jar
  [✔️] copperhopper-0.7.0+1.20.4.jar
  [✔️] craftedcore-3.0-fabric.jar
  [✔️] craftyeyeballs-1.0.0.jar
  [✔️] cristellib-1.2.4-fabric.jar
  [✔️] cubes-without-borders-1.1.0+1.20.jar
  [✔️] deathlog-0.3.2+1.20.3.jar
  [✔️] deeperdarker-fabric-1.20.4-1.2.6.jar
  [✔️] DisableCustomWorldsAdvice-5.0.jar
  [✔️] DistinguishedPotions-v20.4.1-1.20.4-Fabric.jar
  [✔️] elytra_trinket-1.0.5.jar
  [✔️] emi-1.1.2+1.20.4+fabric.jar
  [✔️] emitrades-fabric-1.3.0+mc1.20.4.jar
  [✔️] EnchantmentDescriptions-Fabric-1.20.4-20.0.2.jar
  [✔️] enchantment-lore-1.3.4+MC1.20.3-1.20.4.jar
  [✔️] enhancedblockentities-0.9.1+1.20.2.jar
  [✔️] entity_model_features_fabric_1.20.4-1.2.3.jar
  [✔️] entity_texture_features_fabric_1.20.4-5.2.3.jar
  [✔️] entityculling-fabric-1.6.3.1-mc1.20.4.jar
  [✔️] EquipmentCompare-1.20.2-fabric-1.3.8.jar
  [✔️] essential_1-3-1_fabric_1-20-4.jar
  [✔️] explosive-enhancement-1.2.2-1.20.x.jar
  [✔️] fabric-api-0.96.4+1.20.4.jar
  [✔️] fabric-end-remastered-5.2.4.jar
  [✔️] fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar
  [✔️] fabrishot-1.12.1.jar
  [✔️] FactoryAPI-1.20.4-2.1.2-fabric.jar
  [✔️] ferritecore-6.0.3-fabric.jar
  [✔️] fishontheline-1.20.4-3.2.jar
  [✔️] ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
  [✔️] friendsandfoes-beekeeperhut-fabric-mc1.20.4-2.0.0.jar
  [✔️] friendsandfoes-fabric-mc1.20.4-2.0.9.jar
  [✔️] friendsandfoes-flowerymooblooms-fabric-mc1.20.4-2.0.1.jar
  [✔️] fusion-1.1.1-fabric-mc1.20.4.jar
  [✔️] geckolib-fabric-1.20.4-4.4.2.jar
  [✔️] grapplemod-1.20.4-v1.7.jar
  [✔️] guardvillagers-2.0.9-1.20.4.jar
  [✔️] handcrafted-fabric-1.20.4-3.2.1.jar
  [✔️] hero-proof-5.1.1.jar
  [✔️] HideModded-1.0.1.jar
  [✔️] Highlighter-1.20.2-fabric-1.1.9.jar
  [✔️] HopoBetterRuinedPortals-[1.20.2-1.20.4]-1.3.8.jar
  [✔️] HopoBetterUnderwaterRuins-[1.20.2-1.20.4]-1.1.5.jar
  [✔️] Iceberg-1.20.4-fabric-1.1.18.jar
  [✔️] ImmediatelyFast-Fabric-1.2.10+1.20.4.jar
  [✔️] indium-1.0.30+mc1.20.4.jar
  [✔️] integrated-circuit-1.20.4-1.4.1.jar
  [✔️] inventorymanagement-1.5.0+1.20.3.jar
  [✔️] iris-mc1.20.4-1.6.17.jar
  [✔️] ItemBorders-1.20.2-fabric-1.2.1.jar
  [✔️] Jade-1.20.4-fabric-13.3.1.jar
  [✔️] konkrete_fabric_1.8.0_MC_1.20.4.jar
  [✔️] language-reload-1.5.10+1.20.3.jar
  [✔️] largefluidtank-fabric-20.12.0.jar
  [✔️] lavender-0.1.4+1.20.3.jar
  [✔️] linkart-5.4.1-1.20.2.jar
  [✔️] lithium-fabric-mc1.20.4-0.12.1.jar
  [✔️] mcw-bridges-2.1.0-mc1.20.4fabric.jar
  [✔️] mcw-doors-1.1.0-mc1.20.4fabric.jar
  [✔️] mcw-fences-1.1.1-mc1.20.4fabric.jar
  [✔️] mcw-furniture-3.2.2-mc1.20.4fabric.jar
  [✔️] mcw-holidays-1.1.0-mc1.20.4fabric.jar
  [✔️] mcw-lights-1.0.6-mc1.20.4fabric.jar
  [✔️] mcw-paintings-1.0.5-1.20.4fabric.jar
  [✔️] mcw-paths-1.0.4fabric-mc1.20.4.jar
  [✔️] mcw-roofs-2.3.0-mc1.20.4fabric.jar
  [✔️] mcw-trapdoors-1.1.2-mc1.20.4fabric.jar
  [✔️] mcw-windows-2.2.1-mc1.20.4fabric.jar
  [✔️] midnightlib-fabric-1.5.3.jar
  [✔️] ModDetectionPreventer+1.20.4-1.1.0.jar
  [✔️] modernfix-fabric-5.13.0+mc1.20.4.jar
  [✔️] mod-loading-screen-1.0.4.jar
  [✔️] modmenu-9.0.0.jar
  [✔️] MoreBeeInfo-fabric-1.20-1.1.2.jar
  [✔️] morechathistory-1.3.0.jar
  [✔️] MoreChestVariants-1.5.0+1.20.4-Fabric.jar
  [✔️] moreculling-1.20.4-0.22.1.jar
  [✔️] movingelevators-1.4.6-fabric-mc1.20.4.jar
  [✔️] MutantMonsters-v20.4.0-1.20.4-Fabric.jar
  [✔️] nbtexporter-1.20-1.2-fabric.jar
  [✔️] niftycarts-3.3.0+1.20.4.jar
  [✔️] NoChatReports-FABRIC-1.20.4-v2.5.0.jar
  [✔️] noisium-1.0.2+mc1.20.x.jar
  [✔️] no-telemetry-1.8.0.jar
  [✔️] nvidium-0.2.6-beta.jar
  [✔️] owo-lib-0.12.5+1.20.3.jar
  [✔️] paginatedadvancements-2.4.2.jar
  [✔️] pottery-1.0.1-fabric-mc1.20.4.jar
  [✔️] Prism-1.20.4-fabric-1.0.6.jar
  [✔️] puzzle-1.6.1+1.20.4.jar
  [✔️] PuzzlesLib-v20.4.31-1.20.4-Fabric.jar
  [✔️] Quad-1.1.0+1.20.4-Fabric.jar
  [✔️] raised-fabric-1.20.4-3.1.2.jar
  [✔️] random-fishing-crates-1.3.1.jar
  [✔️] rechiseled-1.1.5b-fabric-mc1.20.jar
  [✔️] reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
  [✔️] resourcefullib-fabric-1.20.4-2.4.7.jar
  [✔️] ResourcePackOverrides-v20.4.2-1.20.4-Fabric.jar
  [✔️] Resourcify (1.20.2+-fabric)-1.3.1.jar
  [✔️] rrls-4.0.2+mc1.20.4-fabric.jar
  [✔️] scalable-cats-force-fabric-2.2.0.jar
  [✔️] seamless-loading-screen-2.1.1+1.20.4-fabric.jar
  [✔️] Searchables-fabric-1.20.4-1.0.3.jar
  [✔️] shifty-hotbar-mc1.20-1.1.jar
  [✔️] simple-armor-hud-1.20.4-1.4.1.jar
  [✔️] SimpleCopperPipes-1.20.4-1.16.1.jar
  [✔️] smoothmenu-1.1.0.jar
  [✔️] snuffles-1.1.0+1.20.4.jar
  [✔️] sodium-fabric-0.5.8+mc1.20.4.jar
  [✔️] Soothing Button-0.3 (1.20.4).jar
  [✔️] sparsestructures-2.1.2.jar
  [✔️] starlight-1.1.3+fabric.f5dcd1a.jar
  [✔️] starterkit-1.20.4-6.0.jar
  [✔️] status-effect-bars-1.0.4.jar
  [✔️] stendhal-1.4.1-1.20.2.jar
  [✔️] Stoneworks-v20.4.0-1.20.4-Fabric.jar
  [✔️] supermartijn642configlib-1.1.8a-fabric-mc1.20.2.jar
  [✔️] supermartijn642corelib-1.1.17-fabric-mc1.20.3.jar
  [✔️] The_Graveyard_3.2_(FABRIC)_for_1.20.4.jar
  [✔️] things-0.3.4+1.20.3.jar
  [✔️] threadtweak-fabric-1.20.4-0.1.2.jar
  [✔️] TinySkeletons-v20.4.1-1.20.4-Fabric.jar
  [✔️] toms_storage_fabric-1.20.4-1.6.11.jar
  [✔️] ToolStats-Fabric-1.20.4-19.0.3.jar
  [✔️] Towns-and-Towers-1.12.0.jar
  [✔️] trashcans-1.0.18-fabric-mc1.20.jar
  [✔️] travelers-backpack-1.20.4-9.4.0.jar
  [✔️] TravelersTitles-1.20.4-Fabric-4.4.0.jar
  [✔️] trimeffects-1.1.0-fabric.jar
  [✔️] trinkets-3.8.0.jar
  [✔️] tru.e-ending-v1.1.0b.jar
  [✔️] villager-hats-1.6.2+1.20.jar
  [✔️] villagernames-1.20.4-7.3.jar
  [✔️] vmp-fabric-mc1.20.4-0.2.0+beta.7.138-all.jar
  [✔️] voicechat-fabric-1.20.4-2.5.6.jar
  [✔️] walkers-2.1-fabric.jar
  [✔️] waypoints-vanilla-1.0-Beta.5.jar
  [✔️] woodenhoppers-1.7.0.jar
  [✔️] yacg-2023.12.1.jar
  [✔️] yet-another-config-lib-fabric-3.3.2+1.20.4.jar
  [✔️] yosbr-0.1.2.jar
  [✔️] your-reputation-0.2.5+jade.1.20.jar
  [✔️] YungsApi-1.20.4-Fabric-4.4.1.jar
  [✔️] YungsBetterDesertTemples-1.20.4-Fabric-3.4.0.jar
  [✔️] YungsBetterDungeons-1.20.4-Fabric-4.4.0.jar
  [✔️] YungsBetterEndIsland-1.20.4-Fabric-2.4.0.jar
  [✔️] YungsBetterJungleTemples-1.20.4-Fabric-2.4.0.jar
  [✔️] YungsBetterMineshafts-1.20.4-Fabric-4.4.0.jar
  [✔️] YungsBetterNetherFortresses-1.20.4-Fabric-2.4.0.jar
  [✔️] YungsBetterOceanMonuments-1.20.4-Fabric-3.4.0.jar
  [✔️] YungsBetterStrongholds-1.20.4-Fabric-4.4.0.jar
  [✔️] YungsBetterWitchHuts-1.20.4-Fabric-3.4.0.jar
  [✔️] YungsBridges-1.20.4-Fabric-4.4.0.jar
  [✔️] YungsExtras-1.20.4-Fabric-4.4.0.jar
  [✔️] zombiehorsespawn-1.20.4-4.8.jar
  [✔️] Zoomify-2.13.0.jar

</details>

# Other notes

**Comment by Fisch37** [comment]
Is it possible you tried to craft the book inside the table? Because you need to throw the items onto the crafting table. That being said #5 and #4 are still an issue in the current release. Unfortunately I have been quite busy and thus unable to test and release the current fixes.

**Comment by Fisch37** [comment]
If you need a working version Beta.4 may still work as long as you have cheats enabled

**Comment by Fisch37** [comment]
@viktordimov I am unable to reproduce this issue. Your mod list reveals you are using 1.20.4 which is where I tested. For completeness I also tried 1.20.1, but was unable to reproduce the issue there as well.

**Are you trying to craft the books together in the crafting table?**
If you are, try throwing the items onto the crafting table instead. 
If the issue still occurs, please check the output log of your game for errors and warnings.

**Comment by Fisch37** [comment]
Closed for inactivity
