### ISSUE TITLE
How do you put waypoints into a teleport book? Doesn't work in 1.20.4

### ISSUE THREAD

**Issue by bonsaibauer** [Fisch37/waypoints-vanilla#7]
# Bug Description
How do you put waypoints into a teleport book? Doesn't work in 1.20.4

# Expected Behaviour
version 1.0-beta.5+mod

# Steps to Reproduce
1. Throw Waypoint (signed) and Waypoint Book onto a Cartography Table
2. There is no fusion

# Used Version
1.20.4

# Additional Specifications
Fabric

**Comment by Fisch37** [comment]
This is a known bug (see #5) and is fixed in the current development build.
A release was scheduled but is delayed indefinitely until I have time to fix the compatibility issues inherent in it.
